services:
  # ===========================
  # PROFILE: scaffold
  # ===========================

  api-env:
    profiles: [ "scaffold" ]
    image: maven:3.9-eclipse-temurin-25
    container_name: api-env
    working_dir: /workspace
    volumes:
      - ./api:/workspace
    command: tail -f /dev/null

  front-env:
    profiles: [ "scaffold" ]
    image: node:24-alpine
    container_name: front-env
    working_dir: /app
    volumes:
      - ./front:/app
    command: tail -f /dev/null

  # ===========================
  # PROFILE: dev
  # ===========================

  db:
    profiles: [ "dev" ]
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    profiles: [ "dev" ]
    image: maven:3.9-eclipse-temurin-25
    container_name: api
    working_dir: /workspace
    volumes:
      - ./api:/workspace
      - m2_cache:/root/.m2
    command: >
      bash -lc " apt-get update && apt-get install -y --no-install-recommends inotify-tools && ( while inotifywait -qq -r -e close_write,create,delete,move src; do
          mvn -q -DskipTests compile;
        done ) & 
      mvn -q spring-boot:run "
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SERVER_PORT: 8080
      CORS_ORIGINS: ${CORS_ORIGINS}
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
    ports:
      - "8080:8080"
    depends_on:
      - db

  front:
    profiles: [ "dev" ]
    image: node:24-alpine
    container_name: web
    working_dir: /app
    volumes:
      - ./front:/app
    command: sh -lc "npm install && CHOKIDAR_USEPOLLING=1 WATCHPACK_POLLING=true npm run dev -- -p 3000 -H 0.0.0.0"
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "1"
      WATCHPACK_POLLING: "1"
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  db_data:
  m2_cache:
