spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://db:5432/newstackdb
    username: root
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        multiTenancy: SCHEMA
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

cors:
  allowed-origins: ${CORS_ORIGINS}

jwt:
  expiration: 3600000
  secret: "$2a$12$JCKkDfTqoVIZrPhhEtiQbeZzfSURIB2/Hp9ZSoJe7Fx3vzLAOniZm"
